default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock
development:
  <<: *default
  host: db
  database: myapp_development
test:
  <<: *default
  host: db
  database: myapp_test
